[package]
name = "e2g"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
gtk = "0.17.1"
glib = "0.17.1"
